Resources:
  IAMMP3ITSA:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: customerManagedEC2ReadOnlyPolicy 
      Description: Customer managed policy for read only access to EC2 instance
      Path: '/'
      PolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: Allow
            Action: 
              - 'ec2:Describe'
            Resource: '*'