FROM python:3.8
ENV PYTHONDONTWRITEBYTECODE=1
#PYTHONDONTWRITEBYTECODE: Prevents Python from writing pyc files to disc (equivalent to python -B option)

ENV PYTHONUNBUFFERED=1
#PYTHONUNBUFFERED: Prevents Python from buffering stdout and stderr (equivalent to python -u option)
EXPOSE 8000
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

CMD ["python3","manage.py" ,"runserver","0.0.0.0:8000"]